# Generated by Django 4.2.1 on 2024-03-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
    ]
